/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yzlmproje;

/**
 *
 * @author yc_ke
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btndanismangit = new javax.swing.JButton();
        btparcacigit = new javax.swing.JButton();
        btndanismanisl = new javax.swing.JButton();
        btnteknisyenisl = new javax.swing.JButton();
        btnyikamaciisl = new javax.swing.JButton();
        btnparcaciisl = new javax.swing.JButton();
        btnformenisl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Paneli");

        btndanismangit.setText("Danışman Paneline Geçiş");
        btndanismangit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanismangitActionPerformed(evt);
            }
        });

        btparcacigit.setText("Parçacı Paneline Geçiş");
        btparcacigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btparcacigitActionPerformed(evt);
            }
        });

        btndanismanisl.setText("Danışman Listele, Ekle , Sil ,Düzenle");
        btndanismanisl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanismanislActionPerformed(evt);
            }
        });

        btnteknisyenisl.setText("Teknisyen  Listele, Ekle , Sil ,Düzenle");
        btnteknisyenisl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnteknisyenislActionPerformed(evt);
            }
        });

        btnyikamaciisl.setText("Yıkamacı  Listele, Ekle , Sil ,Düzenle");
        btnyikamaciisl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyikamaciislActionPerformed(evt);
            }
        });

        btnparcaciisl.setText("Parçacı  Listele, Ekle , Sil ,Düzenle");
        btnparcaciisl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparcaciislActionPerformed(evt);
            }
        });

        btnformenisl.setText("Formen  Listele, Ekle , Sil ,Düzenle");
        btnformenisl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformenislActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btndanismanisl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnteknisyenisl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnyikamaciisl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnparcaciisl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnformenisl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btparcacigit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndanismangit)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndanismanisl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnteknisyenisl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnyikamaciisl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnparcaciisl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnformenisl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndanismangit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btparcacigit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndanismangitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanismangitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        danisman d = new danisman();
        d.setFlag(1);
        d.show();
    }//GEN-LAST:event_btndanismangitActionPerformed

    private void btndanismanislActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanismanislActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        danismanIslem di = new danismanIslem();
        di.show();
    }//GEN-LAST:event_btndanismanislActionPerformed

    private void btnteknisyenislActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnteknisyenislActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        teknisyenIslem ti = new teknisyenIslem();
        ti.show();
    }//GEN-LAST:event_btnteknisyenislActionPerformed

    private void btnyikamaciislActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyikamaciislActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        yikamaciIslem yı = new yikamaciIslem();
        yı.show();
    }//GEN-LAST:event_btnyikamaciislActionPerformed

    private void btnparcaciislActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparcaciislActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parcaciIslem pi = new parcaciIslem();
        pi.show();
    }//GEN-LAST:event_btnparcaciislActionPerformed

    private void btnformenislActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformenislActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        formenIslem fı = new formenIslem();
        fı.show();
    }//GEN-LAST:event_btnformenislActionPerformed

    private void btparcacigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btparcacigitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        depoIslem p = new depoIslem();
        p.show();
    }//GEN-LAST:event_btparcacigitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndanismangit;
    private javax.swing.JButton btndanismanisl;
    private javax.swing.JButton btnformenisl;
    private javax.swing.JButton btnparcaciisl;
    private javax.swing.JButton btnteknisyenisl;
    private javax.swing.JButton btnyikamaciisl;
    private javax.swing.JButton btparcacigit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
