/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yzlmproje;

import javax.swing.JOptionPane;

/**
 *
 * @author yc_ke
 */
public class danisman extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    static int flag=0;
    public danisman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnservisislem = new javax.swing.JButton();
        btnmusteriolustur = new javax.swing.JButton();
        btnmusterisil = new javax.swing.JButton();
        btnmusteridüzenle = new javax.swing.JButton();
        btnislemgor = new javax.swing.JButton();
        btnaracgor = new javax.swing.JButton();
        btnmusterigor = new javax.swing.JButton();
        btnislemdüzenle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnaracolustur = new javax.swing.JButton();
        btnteknisyengor = new javax.swing.JButton();
        btnyikamacigor = new javax.swing.JButton();
        btnadmingit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnservisislem.setText("Servis İşlemi Aç");
        btnservisislem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnservisislemActionPerformed(evt);
            }
        });

        btnmusteriolustur.setText("Müşteri Oluştur");
        btnmusteriolustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmusteriolusturActionPerformed(evt);
            }
        });

        btnmusterisil.setText("Müşteri Sil");
        btnmusterisil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmusterisilActionPerformed(evt);
            }
        });

        btnmusteridüzenle.setText("Müşteri Düzenle");
        btnmusteridüzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmusteridüzenleActionPerformed(evt);
            }
        });

        btnislemgor.setText("Servis İşlem Geçmişi Gör");
        btnislemgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnislemgorActionPerformed(evt);
            }
        });

        btnaracgor.setText("Kayıtlı Tüm Araçları Gör");
        btnaracgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaracgorActionPerformed(evt);
            }
        });

        btnmusterigor.setText("Kayıtlı Tüm Müşterileri Gör");
        btnmusterigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmusterigorActionPerformed(evt);
            }
        });

        btnislemdüzenle.setText("Servis İşlemi Düzenle");
        btnislemdüzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnislemdüzenleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DANIŞMAN YÖNETİM PANELİ");

        btnaracolustur.setText("Araç Oluştur");
        btnaracolustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaracolusturActionPerformed(evt);
            }
        });

        btnteknisyengor.setText("Teknisyen Listesi Gör");
        btnteknisyengor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnteknisyengorActionPerformed(evt);
            }
        });

        btnyikamacigor.setText("Yıkamacı Listesi Gör");
        btnyikamacigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyikamacigorActionPerformed(evt);
            }
        });

        btnadmingit.setText("Admin Paneline Geçiş yap");
        btnadmingit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmingitActionPerformed(evt);
            }
        });

        jLabel2.setText("NOT : Sadece gerekli izinlere sahipseniz admin paneline geçiş yapabilirsiniz.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnmusteriolustur, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(btnaracolustur, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnmusterisil, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnmusteridüzenle, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnmusterigor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnaracgor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnteknisyengor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnyikamacigor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addGap(4, 4, 4))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnservisislem, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnislemdüzenle, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnislemgor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnadmingit, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnislemdüzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnservisislem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnislemgor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmusterisil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmusteriolustur, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmusteridüzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaracolustur, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmusterigor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaracgor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnteknisyengor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnyikamacigor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadmingit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnaracgor, btnaracolustur, btnislemdüzenle, btnislemgor, btnmusteridüzenle, btnmusterigor, btnmusteriolustur, btnmusterisil, btnservisislem, btnteknisyengor, btnyikamacigor});

        jLabel2.getAccessibleContext().setAccessibleName("NOT: sadece gerekli izinlere sahipseniz\n admin paneline geçiş yapabilirsiniz");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnservisislemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnservisislemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        islemOlustur io = new islemOlustur();
        io.show();
    }//GEN-LAST:event_btnservisislemActionPerformed

    private void btnmusteriolusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmusteriolusturActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         musteriOlustur ss= new musteriOlustur();
         ss.show();
    }//GEN-LAST:event_btnmusteriolusturActionPerformed

    private void btnmusterisilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmusterisilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        musteriSil ms = new musteriSil();
        ms.show();
        
    }//GEN-LAST:event_btnmusterisilActionPerformed

    private void btnmusteridüzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmusteridüzenleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        musteriDuzenle md = new musteriDuzenle();
        md.show();
    }//GEN-LAST:event_btnmusteridüzenleActionPerformed

    private void btnislemgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnislemgorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        islemListele il = new islemListele();
        il.show();
    }//GEN-LAST:event_btnislemgorActionPerformed

    private void btnaracgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaracgorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        aracListele al = new aracListele();
        al.show();
    }//GEN-LAST:event_btnaracgorActionPerformed

    private void btnmusterigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmusterigorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        musterileriListele ml = new musterileriListele();
        ml.show();
    }//GEN-LAST:event_btnmusterigorActionPerformed

    private void btnislemdüzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnislemdüzenleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        islemDuzenle id = new islemDuzenle();
        id.show();
    }//GEN-LAST:event_btnislemdüzenleActionPerformed

    private void btnaracolusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaracolusturActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        aracOlustur ao = new aracOlustur();
        ao.show();
    }//GEN-LAST:event_btnaracolusturActionPerformed

    private void btnteknisyengorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnteknisyengorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        teknisyenListele tl = new teknisyenListele();
        tl.setFlag(1);
        tl.show();
    }//GEN-LAST:event_btnteknisyengorActionPerformed

    private void btnyikamacigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyikamacigorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        yikamaciListele yl = new yikamaciListele();
        yl.show();
    }//GEN-LAST:event_btnyikamacigorActionPerformed

    private void btnadmingitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmingitActionPerformed
        // TODO add your handling code here:
       if(flag==1){
        this.setVisible(false);
        admin a = new admin();
        a.show();   
       }else{
           JOptionPane.showMessageDialog(null,"Giriş Yetkiniz Bulunamamıştır.");
       }
        
    }//GEN-LAST:event_btnadmingitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static int getFlag() {
        return flag;
    }

    public static void setFlag(int flag) {
        danisman.flag = flag;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(danisman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(danisman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(danisman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(danisman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new danisman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmingit;
    private javax.swing.JButton btnaracgor;
    private javax.swing.JButton btnaracolustur;
    private javax.swing.JButton btnislemdüzenle;
    private javax.swing.JButton btnislemgor;
    private javax.swing.JButton btnmusteridüzenle;
    private javax.swing.JButton btnmusterigor;
    private javax.swing.JButton btnmusteriolustur;
    private javax.swing.JButton btnmusterisil;
    private javax.swing.JButton btnservisislem;
    private javax.swing.JButton btnteknisyengor;
    private javax.swing.JButton btnyikamacigor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
