/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yzlmproje;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.BorderLayout;
import javax.swing.DropMode;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author yc_ke
 */
public class parcaIslem extends javax.swing.JFrame {
DefaultTableModel dtm =new DefaultTableModel();
    /**
     * Creates new form parcaIslem
     */
    static String parca_kodu,isim,stok_durum,maliyet;
    public parcaIslem() {
        initComponents();
        dtm.setColumnIdentifiers(new String[]{"parca_kodu","isim","maliyet","stok_durum"});
        jTable1.setModel(dtm);
        setParcaTablosu();
    }
     
      public void setParcaTablosu(){
        try{	
	Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	String url = "jdbc:sqlserver://DESKTOP-ACBIUN1\\DESKTOP-ACBIUN1:1433;databaseName=Proje";
	String user = "admin";
	String password = "sifre123";
	Connection con = DriverManager.getConnection(url, user, password);
        Statement stm = con.createStatement();
        String sql = "SELECT * from Parca";
        ResultSet rs = stm.executeQuery(sql);
        ((DefaultTableModel)jTable1.getModel()).setNumRows(0);
        while(rs.next()){
             parca_kodu=rs.getString("parca_kodu");
                isim=rs.getString("isim");
                maliyet=Integer.toString(rs.getInt("maliyet"));
                stok_durum=Integer.toString(rs.getInt("stok_durum"));
         dtm.addRow(new String[]{rs.getString("parca_kodu"),rs.getString("isim"),Integer.toString(rs.getInt("maliyet")),Integer.toString(rs.getInt("stok_durum"))});
                 }
        con.close();
      }catch(ClassNotFoundException | SQLException e){
         JOptionPane.showMessageDialog(null, e);
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtparcakodu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtisim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtstokdurum = new javax.swing.JTextField();
        btnolustur = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        txtmaliyet = new javax.swing.JTextField();
        btnsil = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnguncelle = new javax.swing.JButton();
        btnbul = new javax.swing.JButton();
        btngeri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btntblo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtparcakodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtparcakoduActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("İsim      : ");

        txtisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtisimActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parça Düzenleme İşlemleri");

        btnolustur.setText("Oluştur");
        btnolustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnolusturActionPerformed(evt);
            }
        });

        jLabel4.setText("Stok_durum              :");

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnsil.setText("Sil");
        btnsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsilActionPerformed(evt);
            }
        });

        jLabel5.setText("Maliyet     :");

        btnguncelle.setText("Güncelle");
        btnguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelleActionPerformed(evt);
            }
        });

        btnbul.setText("Bul");
        btnbul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbulActionPerformed(evt);
            }
        });

        btngeri.setText("Ana menüye Dön");
        btngeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeriActionPerformed(evt);
            }
        });

        jLabel2.setText("Parca Kodu  : ");

        btntblo.setText("Tablo Güncelle");
        btntblo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntbloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(350, 350, 350))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmaliyet, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtstokdurum, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtisim, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtparcakodu, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbul, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnolustur, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addComponent(btnsil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(450, 450, 450)
                                .addComponent(btntblo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btngeri)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtparcakodu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtisim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstokdurum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmaliyet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnolustur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btngeri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btntblo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtparcakoduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtparcakoduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtparcakoduActionPerformed

    private void txtisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtisimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtisimActionPerformed

    private void btnolusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnolusturActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-ACBIUN1\\DESKTOP-ACBIUN1:1433;databaseName=Proje";
            String user = "admin";
            String password = "sifre123";
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stm = con.createStatement();

            parca_kodu = txtparcakodu.getText();
            isim = txtisim.getText();
            stok_durum =  txtstokdurum.getText();
            maliyet =  txtmaliyet.getText();
            String q = "INSERT INTO Parca (parca_kodu,isim,stok_durum,maliyet) VALUES ('"+parca_kodu+"','"+isim+"','"+stok_durum+"','"+maliyet+"')";
            int sonuc = stm.executeUpdate(q);
            if(sonuc==1){
                JOptionPane.showMessageDialog(null,"Tebrikler Kayıt yaptiniz");

                 txtparcakodu.setText("");
                txtmaliyet.setText("");
                txtisim.setText("");
                txtstokdurum.setText("");

            }else{
                JOptionPane.showMessageDialog(null,"Kayıt oluşturulamadı Tekrar deneyiniz");
                  txtparcakodu.setText("");
                txtmaliyet.setText("");
                txtisim.setText("");
                txtstokdurum.setText("");

            }

            con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnolusturActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtparcakodu.setText("");
        txtmaliyet.setText("");
        txtisim.setText("");
        txtstokdurum.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsilActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-ACBIUN1\\DESKTOP-ACBIUN1:1433;databaseName=Proje";
            String user = "admin";
            String password = "sifre123";
            Connection con = DriverManager.getConnection(url, user, password);
            String Id=txtparcakodu.getText();
            String sql = "DELETE  from Parca where parca_kodu=? ";
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1,Id);
            int rows = stm.executeUpdate();
            btnreset.doClick();
            if(rows>0){
                JOptionPane.showMessageDialog(null,"Başarıyla Silindi..");
            }else{
                JOptionPane.showMessageDialog(null,"İslem bulunamadı tekrar Deneyiniz..");
            }
            con.close();
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsilActionPerformed

    private void btnguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelleActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-ACBIUN1\\DESKTOP-ACBIUN1:1433;databaseName=Proje";
            String user = "admin";
            String password = "sifre123";
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stm = con.createStatement();
            parca_kodu = txtparcakodu.getText();
            isim = txtisim.getText();
            stok_durum =  txtstokdurum.getText();
            maliyet =  txtmaliyet.getText();
            //formen_id,ad_soyad,maas,uzmanlik_alani,mesai_saati,is_durumu
            String q = "UPDATE Parca SET maliyet='"+maliyet+"',isim='"+isim+"'" + ",stok_durum='"+stok_durum+"' where parca_kodu='"+parca_kodu+"'";
            int sonuc = stm.executeUpdate(q);
            if(sonuc==1){
                JOptionPane.showMessageDialog(null,"Tebrikler Güncelleme yaptiniz");
                txtparcakodu.setText("");
                txtmaliyet.setText("");
                txtisim.setText("");
                txtstokdurum.setText("");
            }else{
                JOptionPane.showMessageDialog(null,"Güncelleme oluşturulamadı Tekrar deneyiniz");
                txtparcakodu.setText("");
                txtmaliyet.setText("");
                txtisim.setText("");
                txtstokdurum.setText("");
              }

            con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnguncelleActionPerformed

    private void btnbulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbulActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try{

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-ACBIUN1\\DESKTOP-ACBIUN1:1433;databaseName=Proje";
            String user = "admin";
            String password = "sifre123";
            Connection con = DriverManager.getConnection(url, user, password);
            String Id=txtparcakodu.getText();

            Statement stm = con.createStatement();
            String sql = "select *  from Parca where parca_kodu='"+Id+"' ";
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){

                parca_kodu=rs.getString("parca_kodu");
                isim=rs.getString("isim");
                maliyet=Integer.toString(rs.getInt("maliyet"));
                stok_durum=Integer.toString(rs.getInt("stok_durum"));
            }
            btnreset.doClick();
            txtparcakodu.setText(parca_kodu);
            txtmaliyet.setText(maliyet);
            txtisim.setText(isim);
            txtstokdurum.setText(stok_durum);
            con.close();
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnbulActionPerformed

    private void btngeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeriActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        depoIslem dp = new depoIslem();
        dp.show();
    }//GEN-LAST:event_btngeriActionPerformed

    private void btntbloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntbloActionPerformed
        // TODO add your handling code here:
        setParcaTablosu();
    }//GEN-LAST:event_btntbloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parcaIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parcaIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parcaIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parcaIslem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parcaIslem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbul;
    private javax.swing.JButton btngeri;
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btnolustur;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsil;
    private javax.swing.JButton btntblo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtisim;
    private javax.swing.JTextField txtmaliyet;
    private javax.swing.JTextField txtparcakodu;
    private javax.swing.JTextField txtstokdurum;
    // End of variables declaration//GEN-END:variables
}
